### PR TITLE
Update remove-SCCMAgent.ps1 updates

### PR DESCRIPTION
**Pull request by ChadSimmons**
Add removal of program shortcuts, certificates, and WU policies.  Change smart quotes to standard quotes.

### CODE REVIEW

**Comment by ChadSimmons** [comment]
Changes based on my own experience and some code from https://www.optimizationcore.com/deployment/sccm-client-complete-remove-uninstall-powershell-script and https://jamesachambers.com/remove-microsoft-sccm-by-force.   Thanks for publishing the script!

**Review by franklesniak — APPROVED** [review]
These changes look good to me. Can we publish?

**Comment by franklesniak** [comment]
Chad, did you mean to delete the repository? It doesn't look like the changes were merged in.

**Comment by ChadSimmons** [comment]
I didn't mean to delete the repo, I think I deleted the fork and PR when I was cleaning up old stuff.  As it appears this repo is abandoned.
I published a script on my own repo https://github.com/ChadSimmons/Scripts/blob/default/ConfigMgr/Troubleshooting/Remove-MCMClient.ps1

**Pull request closed without merging**
